#!/bin/bash


if [[ "$2" == "err1" ]]; then
    echo "Failed to resolve host: No address associated with hostname" >&2
    exit -1
elif [[ "$2" == "err2" ]]; then
    echo "[ 2][t 0][2025-03-23 14:15:14.540440007][terminal.cpp:102][!terminal io]        disabling readline" >&2
    for i in {1..10} ; do 
        echo "[ 1][t 0][2025-03-23 14:18:36.857873072][adnl-ext-connection.cpp:129][!outconn] Client got error [PosixError : Connection refused : 111 : Error on [fd:5]]" >&2
        echo "[ 2][t 0][2025-03-23 14:18:36.859196683][storage-daemon-cli.cpp:235][!extclient]        Connection closed" >&2
      sleep 1
    done
    exit -1
fi

echo "[ 2][t 0][2025-03-23 14:15:14.540440007][terminal.cpp:102][!terminal io]        disabling readline" >&2
echo "[ 3][t 0][2025-03-23 14:15:14.576307267][storage-daemon-cli.cpp:231][!extclient]        Connected" >&2

if [[ "$2" == "list" ]]; then
    cat << EOF 
{
   "@type" : "storage.daemon.torrentList",
   "torrents" : [
      {
         "@type" : "storage.daemon.torrent",
         "hash" : "qMJ8CvK7OjB3Mw8YV8MTD26+7lvVNHoY8aTM0w1PX4I=",
         "flags" : 3,
         "total_size" : "52",
         "description" : "4c48d157-56fc-5487-b8a5-2e331c2e7e11",
         "files_count" : "1",
         "included_size" : "52",
         "dir_name" : "",
         "downloaded_size" : "52",
         "added_at" : 1742716306,
         "root_dir" : "/storage-db/torrent/torrent-files/A8C27C0AF2BB3A3077330F1857C3130F6EBEEE5BD5347A18F1A4CCD30D4F5F82",
         "active_download" : true,
         "active_upload" : true,
         "completed" : true,
         "download_speed" : 0.000000,
         "upload_speed" : 0.000000,
         "fatal_error" : ""
      }
    ]
}

EOF
elif [[ "$2" == "adderr" ]]; then
    echo "Query error: Cannot add torrent: duplicate hash F70D2F7587DBDFD0928E1967A0B2783EC3ABD63846AEC3B055B4705AEF742871"
elif [[ "$2" == "add" ]]; then
    cat << EOF 
{
    "@type": "storage.daemon.torrentFull", 
    "torrent": {
        "@type": "storage.daemon.torrent", 
        "hash": "9w0vdYfb39CSjhlnoLJ4PsOr1jhGrsOwVbRwWu90KHE=", 
        "total_size": "0", 
        "description": "", 
        "files_count": "0", 
        "included_size": "0", 
        "dir_name": "", 
        "downloaded_size": "0", 
        "added_at": 1742742578, 
        "root_dir": "/storage-db/torrent/torrent-files/F70D2F7587DBDFD0928E1967A0B2783EC3ABD63846AEC3B055B4705AEF742871", 
        "active_download": true, 
        "active_upload": true, 
        "completed": false, 
        "download_speed": 0.0, 
        "upload_speed": 0.0, 
        "fatal_error": ""
    }, 
    "files": []
}
EOF
elif [[ "$2" == "geterr" ]]; then
    echo "Query error: No such torrent"
elif [[ "$2" == "get" ]]; then
    cat << EOF
{
    "@type": "storage.daemon.torrentFull", 
    "torrent": {
        "@type": "storage.daemon.torrent", 
        "hash": "9w0vdYfb39CSjhlnoLJ4PsOr1jhGrsOwVbRwWu90KHE=", 
        "flags": 3, 
        "total_size": "1641519", 
        "description": "Test Assets", 
        "files_count": "3", 
        "included_size": "1641519", 
        "dir_name": "images/", 
        "downloaded_size": "1641519", 
        "added_at": 1742742578, 
        "root_dir": "/storage-db/torrent/torrent-files/F70D2F7587DBDFD0928E1967A0B2783EC3ABD63846AEC3B055B4705AEF742871", 
        "active_download": true, 
        "active_upload": true, 
        "completed": true, 
        "download_speed": 0.0, 
        "upload_speed": 0.0, 
        "fatal_error": ""
    }, 
    "files": [
        {
            "@type": "storage.daemon.fileInfo", 
            "name": "classA.png", 
            "size": "559600", 
            "priority": 1, 
            "downloaded_size": "559600"
        }, 
        {
            "@type": "storage.daemon.fileInfo", 
            "name": "classB.png", 
            "size": "540899", 
            "priority": 1, 
            "downloaded_size": "540899"
        }, 
        {
            "@type": "storage.daemon.fileInfo", 
            "name": "collection.png", 
            "size": "540899", 
            "priority": 1, 
            "downloaded_size": "540899"
        }
    ]
}    
EOF
elif [[ "$2" == "get-peers" ]]; then
    cat << EOF
{
    "@type": "storage.daemon.peerList", 
    "peers": [
        {
            "@type": "storage.daemon.peer", 
            "adnl_id": "kGYfhI+5d44+27ZKj3Z0nAwTtV3alffz+d32DMx9vGk=", 
            "ip_str": "82.148.29.191:3333", 
            "download_speed": 0.0, 
            "upload_speed": 0.0, 
            "ready_parts": "13"
        }
    ], 
    "download_speed": 0.0, 
    "upload_speed": 0.0, 
    "total_parts": "13"
}
EOF
elif [[ "$2" == "remove" ]]; then
    echo "Success"
elif [[ "$2" == "removeerr" ]]; then
    echo "Query error: No such torrent"
elif [[ "$2" == "create" ]]; then
    cat << EOF
{
    "@type": "storage.daemon.torrentFull", 
    "torrent": {
        "@type": "storage.daemon.torrent", 
        "hash": "D65uMOy1/Z0xC6lB3osgq2txYSN9Cy08tx8nyJXAFEk=", 
        "flags": 3, 
        "total_size": "61", 
        "description": "{\"nft_address\": \"kQDggbH8_-FjQOjYgh96uSlZpImO02o9cBberv3BQRfcw7mH\"}", 
        "files_count": "1", 
        "included_size": "61", 
        "dir_name": "", 
        "downloaded_size": "61", 
        "added_at": 1742743853, 
        "root_dir": "/storage-db/torrent/torrent-files/0FAE6E30ECB5FD9D310BA941DE8B20AB6B7161237D0B2D3CB71F27C895C01449", 
        "active_download": false, 
        "active_upload": true, 
        "completed": true, 
        "download_speed": 0.0, 
        "upload_speed": 0.0, 
        "fatal_error": ""
    }, 
    "files": [
        {
            "@type": "storage.daemon.fileInfo", 
            "name": "file1.txt", 
            "size": "4", 
            "priority": 1, 
            "downloaded_size": "4"
        }
    ]
}
EOF
elif [[ "$2" == "createerr" ]]; then
    echo "Query error: File \"C:\\Work\\ton-storage\\file10.txt\" can't be opened for reading for stat"
fi

sleep 5