[tox]
skipsdist = True
envlist =
       {py310},
       isort, flake

[flake8]
max-complexity = 24
max-line-length = 119
exclude =

[coverage:run]
omit =
       */test/*
       __meta__.py
source =
       NFTorrent

[coverage:report]
fail_under = 80.00
precision = 2
exclude_lines =
    pragma: no cover
    @abc.abstractmethod


[testenv]
commands =
    python3 -m unittest {posargs}
passenv =
    CI_*
    PIP_*
setenv =
deps =
    pytest
    -rrequirements.txt

[testenv:coverage]
commands =
    coverage run -m unittest {posargs}
commands_post =    
    coverage report
    coverage html --directory={toxworkdir}/{envname}/htmlcov
    coverage json -o {toxworkdir}/{envname}/coverage.json
deps =
    coverage~=7.0.0

[testenv:isort]
; check that imports are sorted alphabetically
commands =
       isort --check-only --diff nwm_dashboard tests {posargs}
deps =
       isort
 
[testenv:flake]
; Style Guide Enforcement
commands =
       flake8 NFTorrent tests {posargs}
deps =
       flake8       