[tox]
skipsdist = true
envlist =
        {py310},
        isort, flake

[flake8]
max-complexity = 24
max-line-length = 119
exclude =

[coverage:run]
omit =
        */test/*
        NFTorrent/__meta__.py
        NFTorrent/main.py
source =
        NFTorrent

[coverage:report]
fail_under = 80.00
precision = 2
exclude_lines =
        pragma: no cover
        @abc.abstractmethod


[docker:cache]
image = redis:latest
expose =
        TON_API_CACHE_REDIS_PORT=6379/tcp

[docker:db]
image = postgres:latest
environment =
        POSTGRES_PASSWORD=postgres
        POSTGRES_USER=postgres
expose =
        INDEXDB_DATABASE_PORT=5432/tcp

[testenv]
commands =
        python3 -m unittest {posargs}
passenv =
        CI_*
        PIP_*
setenv =
deps =
        pytest
        -rrequirements.txt

[testenv:coverage]
commands =
        coverage run -m unittest {posargs}
commands_post =
        coverage report
        coverage html --directory={toxworkdir}/{envname}/htmlcov
        coverage json -o {toxworkdir}/{envname}/coverage.json
deps =
        coverage~=7.0.0
        -rrequirements.txt

[testenv:isort]
; check that imports are sorted alphabetically
commands =
        isort --check-only --diff NFTorrent test {posargs}
deps =
        isort

[testenv:flake]
; Style Guide Enforcement
commands =
        flake8 NFTorrent test {posargs}
deps =
        flake8

[testenv:server]
; docker =
;         db
;         cache
skip_install = true
setenv =
        UVICORN_LOG_LEVEL=trace
        LOGURU_LEVEL=WARNING
        TON_STORAGE_PUBLIC_ADDR=37.78.117.156
        TON_STORAGE_CLI_BINARY=/mnt/c/Work/ton-storage/storage-daemon-cli.exe
        TON_STORAGE_DAEMON_ADDR=172.19.96.1:5555
        TON_STORAGE_DB_PATH=C:/Work/ton-storage/storage-db
        TON_STORAGE_DB_TORRENT_PATH=/mnt/c/Work/ton-storage/storage-db/torrent/torrent-files
        TON_STORAGE_MANIFEST_BAG_ID=A8C27C0AF2BB3A3077330F1857C3130F6EBEEE5BD5347A18F1A4CCD30D4F5F82
        TON_STORAGE_NUM_WORKERS=4
        TON_STORAGE_MIN_REDUNDANCY=1
        TON_STORAGE_SIZE_PRESSURE=5
        TON_STORAGE_BAG_SIZE_LIMIT=4194304
        TON_STORAGE_CONFIRMATION_TIMEOUT=90
        TON_API_TONLIB_LITESERVER_CONFIG=https://ton.org/testnet-global-config.json
        TON_API_TONLIB_KEYSTORE={toxworkdir}/.ton_keystore/
        TON_API_CACHE_ENABLED={env:CI_CACHE_ENABLED:0}
        TON_API_CACHE_REDIS_ENDPOINT={env:CI_CACHE_HOST:127.0.0.1}
        TON_API_CACHE_REDIS_TIMEOUT=2
        INDEXDB_ENABLED={env:CI_INDEXDB_ENABLED:1}
        INDEXDB_INDEXER_TIMEOUT=10
        INDEXDB_NFTORRENT_APIROOT=https://muratov.xyz/nftorrent
        ; HTTP_API_ROOT_PATH=/nftorrent
        HTTP_API_JWT_SECRET=f53c1ba73b3d00ee88335fb690e6832b72e6a73094e2903661abc2f9bc72d414
        HTTP_VERIFY_SSL=0
        HTTP_ENABLE_SSL=1
        HTTP_TWA_DOMAINS=localhost:9000
        HTTP_ALLOW_NETWORKS=127.0.0.1/32
        HTTP_REMOTE_API_ROOT=/nftorrent
commands =
        uvicorn --log-level info --reload --reload-dir ./NFTorrent NFTorrent.main:app
deps =
        uvicorn
        -rrequirements.txt

[testenv:build]
description = Build python package
deps =
       setuptools
       wheel
       build
commands =
       python3 -m build

[testenv:image]
skip_install = true
description = Build docker image
depends =
       build
allowlist_externals =
        docker
setenv =
        TON_RELEASE={env:CI_TON_RELEASE:v2025.04}
        IMAGE_NFTORRENT={env:CI_IMAGE_NFTORRENT:nft-torrent}
        file|./NFTorrent/__meta__.py
deps =
commands =
        docker build ./docker -t {env:IMAGE_NFTORRENT}:{env:__version__} \
                --build-context dist=./dist \
                --build-arg NFTORRENT_VERSION={env:__version__} \
                --build-arg TON_RELEASE={env:TON_RELEASE}
