- name: 'Public Ceritificates path'
  file:
    path: "/etc/pki/tls/certs/{{ item.domain }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ certs }}"

- name: 'Private Ceritificates path'
  file:
    path: "/etc/pki/tls/private/{{ item.domain }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items: "{{ certs }}"

- name: 'SSL Public Ceritificate'
  copy:
    src: "{{ inventory_dir }}/certs/{{ item.domain }}/{{ item.public_cert }}"
    dest: "/etc/pki/tls/certs/{{ item.domain }}/{{ item.public_cert }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ certs }}"

- name: 'SSL Private Ceritificate Key'
  copy:
    src: "{{ inventory_dir }}/certs/{{ item.domain }}/{{ item.private_key }}"
    dest: "/etc/pki/tls/private/{{ item.domain }}/{{ item.private_key }}"
    owner: root
    group: root
    mode: 0600
  with_items: "{{ certs }}"