- name: '"{{ service.name }}" service read {{ item.name }}'
  command: '/usr/bin/crudini --get /usr/lib/systemd/system/{{ service.name }}.service Service {{ item.name }}'
  register: result
  failed_when: result.rc != 0 and result.rc != 1
  changed_when: False

- name: '"{{ service.name }}" service {{ item.name }}={{ item.value }}'
  command: '/usr/bin/crudini --set /usr/lib/systemd/system/{{ service.name }}.service Service {{ item.name }} "{{ item.value }}"'
  when: result.stdout != item.value
  notify:
    - service daemon_reload
