- name: Setup InfluxData repo (RedHat)
  block:
    - name: "Import InfluxDB GPG Key"
      ansible.builtin.rpm_key:
        state: present
        key: https://repos.influxdata.com/influxdata-archive.key

    - name: "InfluxDB Repository"
      yum_repository:
        name: influxdb
        description: InfluxDB Repository - RHEL
        baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
        gpgkey:  https://repos.influxdata.com/influxdata-archive_compat.key
        gpgcheck: yes
        enabled: yes

  when: ansible_os_family == "RedHat"
  tags: telegraf

- name: Setup InfluxData repo (Debian)
  block:
    - name: Download influxdata archive key
      ansible.builtin.get_url:
        url: https://repos.influxdata.com/influxdata-archive.key
        dest: /tmp/influxdata-archive.key
        mode: '0644'

    - name: Convert influxdata archive key to GPG format
      ansible.builtin.command:
        cmd: >
          gpg --dearmor
          -o /usr/share/keyrings/influxdata-archive.gpg
          /tmp/influxdata-archive.key
      args:
        creates: /usr/share/keyrings/influxdata-archive.gpg

    - name: Remove legacy influxdata trusted.gpg key
      ansible.builtin.file:
        path: /etc/apt/trusted.gpg.d/influxdata-archive.gpg
        state: absent

    - name: Add influxdata APT repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [signed-by=/usr/share/keyrings/influxdata-archive.gpg]
          https://repos.influxdata.com/debian stable main
        state: present
        filename: influxdata

    - name: Remove temporary key
      ansible.builtin.file:
        path: /tmp/influxdata-archive.key
        state: absent

  when: ansible_os_family == "Debian"
  tags: telegraf

- name: '"telegraf" config path'
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/telegraf
  tags: telegraf

- name: '"telegraf" package present'
  dnf:
    name: telegraf
    state: present
  tags: telegraf

- name: '"telegraf" influxdb is configured'
  template:
    src: "./etc/telegraf/telegraf-influxdb.conf"
    dest: /etc/telegraf/telegraf.conf
    owner: telegraf
    group: telegraf
    mode: 0600
  when: oam.telegraf.influxdb is defined
  notify:
    - restart telegraf
  tags: telegraf

- name: '"telegraf" VM is configured'
  template:
    src: "./etc/telegraf/telegraf-vm.conf"
    dest: /etc/telegraf/telegraf.conf
    owner: telegraf
    group: telegraf
    mode: 0600
  when: oam.telegraf.vm is defined
  notify:
    - restart telegraf
  tags: telegraf

- name: '"telegraf" service'
  include_role:
    name: common
    tasks_from: service
  vars:
    service:
      name: telegraf
      package: telegraf
      params: "{{ telegraf.service_params }}"
  tags: telegraf

- name: adding existing user 'telegraf' to group 'docker'
  user:
    name: telegraf
    groups: docker
    append: yes
  tags: telegraf