services:
  # cache:
  #   image: redis:latest
  #   restart: unless-stopped
  #   networks:
  #     - internal

  # db:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #   ports:
  #     - "127.0.0.1:5434:5432"
  #   volumes:
  #     - ./index-db:/var/lib/postgresql/data
  #   networks:
  #     - internal

  ipfs:
    image: ipfs/kubo:release
    restart: unless-stopped
    user: 9001:9001
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8080:8080
    volumes:
      - ./ipfs-db:/data/ipfs
    networks:
      - internal

  ipfs-cluster:
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    depends_on:
      - ipfs
    entrypoint: >
      sh -c 'export CLUSTER_SECRET=$(cat /run/secrets/ipfs_secret) &&
             exec /usr/local/bin/entrypoint.sh daemon'
    environment:
      CLUSTER_PEERNAME: ${NODE_ID}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_IPFSPROXY_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
      CLUSTER_IPFSPROXY_LISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9095
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    secrets:
      - ipfs_secret
    ports:
      - "127.0.0.1:9094:9094"
      - "127.0.0.1:9095:9095"
      - "9096:9096" # Cluster swarm endpoint
    volumes:
      - ./cluster-db:/data/ipfs-cluster
    networks:
      - internal
    healthcheck:
      test: ipfs-cluster-ctl --enc=json health metrics ping
      interval: 15s
      timeout: 3s
      retries: 5

  httpserver:
    image: dtec/nft-torrent:${NFTORRENT_VERSION}
    restart: unless-stopped
    environment:
      LOGGER_CONFIG: NFTorrent.logger.config
      IPFS_ENABLED: 1
      IPFS_KUBO_RPC_URI: http://ipfs-cluster:9095
      IPFS_CLUSTER_RPC_URI: http://ipfs-cluster:9094
      IPFS_MIN_REDUNDANCY: 2
      IPFS_CONFIRMATION_TIMEOUT: 60
      TONLIB_KEYSTORE: /ton_keystore/
      TONLIB_REQUEST_TIMEOUT: 20
      TONLIB_LITESERVER_CONFIG: ${TONLIB_LITESERVER_CONFIG}
      CACHE_ENABLED: 1
      # CACHE_REDIS_ENDPOINT: cache
      # CACHE_REDIS_TIMEOUT: 2
      INDEXDB_ENABLED: 1
      INDEXDB_INDEXER_TIMEOUT: 30
      INDEXDB_DATABASE_HOST: host.docker.internal
      INDEXDB_DATABASE_PORT: 6432
      INDEXDB_DATABASE_NAME: petsmem
      INDEXDB_DATABASE_PASSWORD: file:/run/secrets/db_password
      INDEXDB_ETCD_HOSTS: ${INDEXDB_ETCD_HOSTS}
      INDEXDB_ETCD_CACERT: /run/secrets/ca_cert
      INDEXDB_ETCD_CERT: /run/secrets/tls_cert
      INDEXDB_ETCD_KEY: /run/secrets/tls_key
      # HTTP_API_ROOT_PATH: ${HTTP_API_ROOT_PATH}
      HTTP_NODE_ID: ${NODE_ID}
      HTTP_TESTNET: ${HTTP_TESTNET}
      HTTP_GETGEMS_AUTH: ${HTTP_GETGEMS_AUTH}
      HTTP_IPFS_AUTH: ${HTTP_IPFS_AUTH}
      HTTP_PETSMEM_AUTH: ${HTTP_PETSMEM_AUTH}
      HTTP_PETSMEM_CONTENT_AUTH: ${HTTP_PETSMEM_CONTENT_AUTH}
      HTTP_TONVIEWER_AUTH: ${HTTP_TONVIEWER_AUTH}
      HTTP_BOT_MINIAPP_URL: ${HTTP_BOT_MINIAPP_URL}
      HTTP_API_JWT_SECRET: file:/run/secrets/jwt_key
      HTTP_TWA_BOT_TOKEN: file:/run/secrets/bot_token
      HTTP_TWA_BOT_POLL: 1
      HTTP_TWA_BOT_ADMIN_GROUP_ID: ${HTTP_TWA_BOT_ADMIN_GROUP_ID}
      HTTP_TWA_DOMAINS: localhost:9000,${HTTP_TWA_DOMAINS}
      HTTP_ALLOW_ORIGINS: ${HTTP_ALLOW_ORIGINS}
      HTTP_ALLOW_NETWORKS: 127.0.0.1/32,192.168.0.0/16
      HTTP_REQUEST_TIMEOUT: 20
      HTTP_COLLECTION_CONFIG: nftcollections.config
    volumes:
      - ./ton_keystore:/ton_keystore
      - ./nftcollections.py:/opt/nftorrent/nftcollections.py
      - ./assets:/opt/nftorrent/assets
      - ./log:/opt/nftorrent/log
    secrets:
      - jwt_key
      - bot_token
      - db_password
      - ca_cert
      - tls_cert
      - tls_key
    ports:
      - 127.0.0.1:8002:8002
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: curl -sf http://127.0.0.1:8002/healthcheck
      interval: 15s
      timeout: 3s
      retries: 5
    depends_on:
      - ipfs
      # - db
      # - cache

secrets:
  jwt_key:
    file: ./private/jwt.key
  bot_token:
    file: ./private/bot_token.key
  db_password:
    file: ./private/db_password
  tls_cert:
    file: ./private/certs/client.crt
  tls_key:
    file: ./private/certs/client.key
  ca_cert:
    file: ./private/certs/ca.crt
  ipfs_secret:
    file: ./private/ipfs_cluster.key
networks:
  internal: