{
 "title": "NFTorrent: Overview v2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU: Total",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\r\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\r\n  |> group(columns: [\"_measurement\", \"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU: Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\r\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\r\n  |> group(columns: [\"_measurement\", \"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mem: Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> group(columns: [\"_measurement\", \"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mem: Used",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> group(columns: [\"_measurement\", \"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Storage: Load",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentServer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"load\")\r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "CPU: Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> group(columns: [\"_measurement\", \"com.docker.compose.service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mem: Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> group(columns: [\"com.docker.compose.service\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Storage: Redundancy",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentServer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"redundancy\")\r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\r\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "PG-Cluster: Timeline",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patroni\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"patroni_postgres_timeline\")\r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Etcd Cluster",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"etcd_server\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"etcd_server_has_leader\" or r[\"_field\"] == \"etcd_server_is_leader\")\r\n  |> group(columns: [\"host\"])  \r\n  |> aggregateWindow(every: 30s, fn: sum, createEmpty: false)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Web: Nginx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nginx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"accepts\" or r[\"_field\"] == \"handled\" or r[\"_field\"] == \"requests\")\r\n  |> filter(fn: (r) => r[\"host\"] != \"muratovd.ru\")  \r\n  |> group(columns: [\"_measurement\", \"_field\", \"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true) \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PG-Cluster: Streaming",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patroni\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"patroni_postgres_streaming\")\r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PG-Bouncer: Clients Active",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pgbouncer_pools\")\r\n  |> filter(fn: (r) => r[\"db\"] == \"petsmem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cl_active\")\r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PG Cluster",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patroni\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"patroni_postgres_running\" or r[\"_field\"] == \"patroni_primary\")\r\n  |> group(columns: [\"host\"])  \r\n  |> aggregateWindow(every: 30s, fn: sum, createEmpty: false)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Index DB: Collections",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentIndexerColl\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bc_next_index\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> group(columns: [])  \r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentIndexerColl\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bc_next_index\")\r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "NFTorrent: Bot",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentServer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bot\")  \r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Net: Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_bytes\" or r[\"_field\"] == \"tx_bytes\")\r\n  |> group(columns: [\"_measurement\", \"com.docker.compose.service\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true) \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "IndexDB: Species",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    count(*) AS count,\r\n    CASE t.species\r\n        WHEN 0 THEN 'Other'\r\n        WHEN 1 THEN 'Dog'\r\n        WHEN 2 THEN 'Cat'\r\n        WHEN 3 THEN 'Hamster/Guinea Pig'\r\n        WHEN 4 THEN 'Rabbit'\r\n        WHEN 5 THEN 'Parrot'\r\n        WHEN 6 THEN 'Fish'\r\n        WHEN 7 THEN 'Turtle'\r\n        WHEN 8 THEN 'Reptile'\r\n        WHEN 9 THEN 'Horse/Pony'\r\n        WHEN 10 THEN 'Reserved'\r\n        WHEN 11 THEN 'Reserved'\r\n        WHEN 12 THEN 'Reserved'\r\n        WHEN 13 THEN 'Reserved'\r\n        WHEN 14 THEN 'Reserved'\r\n        WHEN 15 THEN 'Reserved'\r\n        ELSE 'Unknown'\r\n    END AS species_name\r\nFROM pet_memory_nft t\r\nGROUP BY t.species\r\nORDER BY t.species;"
    }
   ]
  },
  {
   "title": "NFTorrent: Tonlib",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentServer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tonlib\")  \r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "NFTorrent: Storage",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentServer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"storage\")  \r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "IndexDB: Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentBotBackendDb\")\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])   \r\n  |> group(columns: [\"_field\"])   \r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "IndexDB: Tg Users",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT t.country, count(distinct t.user_id) as count\r\nFROM tg_user t\r\nGROUP BY t.country\r\n"
    }
   ]
  },
  {
   "title": "NFTorrent: IndexDB",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentServer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"indexdb\")  \r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "API: Bootstrap - Country",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentHTTPUsers\")\r\n  |> filter(fn: (r) => r[\"path\"] == \"/api/v1/bootstrap\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"country\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)    \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "API: Auth Poll -Country",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentHTTPUsers\")\r\n  |> filter(fn: (r) => r[\"path\"] == \"/api/v1/account/auth\" or r[\"path\"] == \"/api/v1/account/authPayload\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"country\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)    \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "API: Bootstrap - Browser",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentHTTPUsers\")\r\n  |> filter(fn: (r) => r[\"path\"] == \"/api/v1/bootstrap\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"browser\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)    \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "API: Auth Poll - Browser",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentHTTPUsers\")\r\n  |> filter(fn: (r) => r[\"path\"] == \"/api/v1/account/auth\" or r[\"path\"] == \"/api/v1/account/authPayload\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"browser\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)    \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "API: NFT Content - Country",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentHTTPUsers\")\r\n  |> filter(fn: (r) => r[\"path\"] == \"/c/{address}\" or r[\"path\"] == \"/c/{address}/{digest}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"country\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)    \r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "API: NFT - Country",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"petsmem\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NFTorrentHTTPUsers\")\r\n  |> filter(fn: (r) => r[\"path\"] == \"/api/v1/nft/{address}\" or r[\"path\"] == \"/api/v1/nft/{address}/ipfs/{digest}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"country\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)    \r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}