log_format  main_geo  '$remote_addr[$http_x_real_ip] - $remote_user [$time_local] $host[$geoip2_continent_code:$geoip2_country_code:$geo_target] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

resolver 1.1.1.1 8.8.8.8 valid=300s;
resolver_timeout 3s;

# Load GeoIP2 data from MaxMind database
geoip2 /etc/nginx/GeoLite2-Country.mmdb {
    auto_reload 5m;
    $geoip2_country_code source=$client_ip country iso_code;
    $geoip2_continent_code source=$client_ip continent code;
}

# First map: match specific countries to backend nodes
map $geoip2_country_code $country_target {
    RU          ru.petsmem.site;
    default     "";
}

# Second map: match continent if no country match
map $geoip2_continent_code $continent_target {
    default     {{ webserver.default_domain }};
    EU          eu.petsmem.site;
    # AS          asia.petsmem.site;
}

# Final target selection: prefer country if available, otherwise continent
map $country_target $geo_target {
    default $continent_target;
    ""      $continent_target;
    ~.+     $country_target;
}