set $this_node {{ local_domain }};

{% for route in geoip.proxy_routes %}
location {{ route }} {
    access_log      /var/log/nginx/geo-access.log main_geo;

    if ($geo_target = $this_node) {
        return 302 https://$this_node$request_uri;
    }
    if ($http_x_forwarded_host = "{{ ssl_domain }}") {
        return 302 https://$this_node$request_uri;
    }

    proxy_pass https://$geo_target$request_uri;

    proxy_ssl_server_name on;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host "{{ ssl_domain }}";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_connect_timeout 2s;
    proxy_read_timeout 2s;

    error_page 502 503 504 = @fallback;
}
{% endfor %}

location @fallback {
    access_log      /var/log/nginx/geo-access.log main_geo;

    return 302 https://$this_node$request_uri;
}