- name: '"Testnet" website'
  include_role:
    name: nginx
    tasks_from: website
    apply:
      tags:
        - website
        - testnet
  vars:
    nginx_website:
      target: /usr/share/nginx/html_testnet
      package: "{{ website.package_testnet }}"
  tags:
    - website
    - testnet

- name: '"Mainnet" website'
  include_role:
    name: nginx
    tasks_from: website
    apply:
      tags:
        - website
        - mainnet
  vars:
    nginx_website:
      target: /usr/share/nginx/html
      package: "{{ website.package_mainnet }}"
  tags:
    - website
    - mainnet