[[inputs.prometheus]]
  urls = ["http://localhost:8018/metrics"]
  name_override = "patroni"
  metric_version = 2

[[inputs.prometheus]]
  urls = ["https://127.0.0.1:2379/metrics"]

  fieldpass = ["etcd_server_*"]
  name_override = "etcd_server"
  metric_version = 2

  tls_ca = "/etc/ssl/pgcluster/ca.crt"
  tls_cert = "/etc/telegraf/etcd-client.crt"
  tls_key = "/etc/telegraf/etcd-client.key"

  insecure_skip_verify = true

[[inputs.pgbouncer]]
  address = "host=127.0.0.1 port=6432 user=telegraf password=hZD+0Puc6C2R3Pzd0q+o8dSq dbname=pgbouncer sslmode=disable"
