- name: "Nginx conf.d path"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/nginx/conf.d
  tags: nginx

- name: 'Nginx user group'
  group:
    name: nginx
    state: present
  tags: nginx

- name: Nginx user
  user:
    name: nginx
    state: present
    groups:
      - nginx
    create_home: no
    append: yes
  tags: nginx

- name: Nginx is configured
  copy:
    src: ./etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  tags: nginx

- name: GeoIP
  include_tasks:
    file: geoip.yaml
    apply:
      tags: nginx
  when: webserver.geoip
  tags:
    - nginx
    - geoip

- name: '"Nginx" service'
  include_tasks:
    file: ./../common/tasks/service.yaml
    apply:
      tags: nginx
  vars:
    service:
      name: nginx
      package: nginx
      exclude:
      params: "{{ nginx.service_params }}"
  tags: nginx

# - name: Certbot present packages
#   dnf:
#     name: "{{ packages }}"
#     state: present
#   vars:
#     packages:
#       - certbot
#       - python3-certbot-nginx
#   tags: nginx

- name: "RedHat: Nginx Firewall services"
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - http
    - https
  when: ansible_os_family == "RedHat"
  tags: nginx

- name: "Debian: Nginx Firewall through UFW"
  ansible.builtin.ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - http
    - https
  when: ansible_os_family == "Debian"
  tags: nginx

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_os_family == "RedHat"
  tags: nginx

