server {
    if ($host = www.petsmem.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = petsmem.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name petsmem.ru www.petsmem.ru;

    return 301 https://petsmem.site$request_uri;




}

server {
    listen 443 ssl;
    server_name petsmem.ru www.petsmem.ru;


    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    return 301 https://petsmem.site/ru$request_uri;

    ssl_certificate /etc/letsencrypt/live/petsmem.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/petsmem.ru/privkey.pem; # managed by Certbot

}
